[package]
name = "minish-random"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.4.0"
rand = "0.8.4"
regex = "1.5.4"
scryer-prolog = "0.8.127"
